### ISSUE TITLE
No issue - Question

### ISSUE THREAD

**Issue by quintendewilde** [raspberry-pi-camera/raspindi#1]
Hi, 

Is it possible to capture 2 ndi camera's (thru a switch) and stream these to an ip with a raspberry? 
With this code I mean or is this beyond the capacities of this hub?

Kind regards,

**Comment by rf152** [comment]
I'm not 100% sure what you're asking.

It is possible to have multiple cameras on a network and stream with NDI, and as such this software will allow you to do that. Just have multiple units on the same network, and they'll appear in your NDI receiver.

**Comment by quintendewilde** [comment]
It's exactly what I want! Just quick follow up question. Just install the build.sh?
