### ISSUE TITLE
Upgrade NDI library to NDI 5

### ISSUE THREAD

**Issue by rf152** [raspberry-pi-camera/raspindi#19]
With the announcement today of NDI 5, I would like to look at using NDI 5 as the library.

It reports to have performance improvements, as well as new features.

**Comment by andreicaba** [comment]
are you using the fkms driver?... vlc has great performance using that (for the moment, only on 32 bit systems :) ... I would recommend using DietPI for that - it's actually raspbian, but really optimised). If you can create a NDI 5 source over fkms on the raspberry pi 4 - this would really rock!... :)
Also - rpi4 has wifi over 5ghz so, as NDI 5 brags that it fixed some NDI over WiFi problems... I would say that it's really worth a shot!... :)
And... combined with a FullHD capture card... would make a great (cheap) NDI 5 video source for church broadcasting!... :)

**Comment by yomebzh** [comment]
Hello,
I installed the ND5 library with the new dedicated driver for rpi4 and it works fine.

**Comment by miniman13** [comment]
Is this issue still open? I see that in the changelog "
Upgraded NDI library to v5.0.0" 
However the library in the lib/ndi folder still shows 4.6. 

I believe that with NDI 5 we could possibily use NDI HX3?

**Comment by ijaiii** [comment]
Hello, id like to ask about this since i havent got a pi camera and just a webcam and 3b+, planning to get a rev1.3 for testing. Been struggling with 1080p using dicaffeine with webcam even 720p. I volunteer on a small church, im planning on making a permanent small cam for livestream *been using phone with ndihx*. 
Just want to ask if this can perform true to 1080p30 using pi cam?  Thank you

**Comment by yomebzh** [comment]
hello, I use a pi3 b+ and 8 pi4 ptz to film in 1080p 30 for music groups on my youtube channel

_- removed link to channel_

**Comment by rf152** [comment]
> Is this issue still open? I see that in the changelog " Upgraded NDI library to v5.0.0" However the library in the lib/ndi folder still shows 4.6.
> 
> I believe that with NDI 5 we could possibily use NDI HX3?

The upgrade to NDI5 is under test at the moment. 

As to whether HX3 could be used, I'm not sure. Because my use case is not bandwidth limited, it's not something that I've looked at, however if you want to look into it, then that is fine. If you submit a pull request then I'll happily consider it for inclusion.

**Comment by rf152** [comment]
> Hello, id like to ask about this since i havent got a pi camera and just a webcam and 3b+, planning to get a rev1.3 for testing. Been struggling with 1080p using dicaffeine with webcam even 720p. I volunteer on a small church, im planning on making a permanent small cam for livestream _been using phone with ndihx_. Just want to ask if this can perform true to 1080p30 using pi cam? Thank you

I've been running mine at 1920x1080 without issue. As to whether it hits 30fps, I'm not sure; it is smooth enough for what I need it for, so have no need to check the framerate.

**Comment by miniman13** [comment]
What I have noticed is with the RPI3, it can run fine at 1080p30, but it has much more delay than with the RPI4. I will stage a comparison shot of latency and update the ReadMe with my findings.

**Comment by miniman13** [comment]
I have done some testing with the RPI3 and the RPI4 to determine latency differences, 
the RPI3 at 1280x720/30 has about 600ms of latency, while the RPI4 has 200ms of latency. I believe this is due to the faster RAM on the RPi4. 

<img width="1889" alt="rpidelay_topleft_RPI4_bottomleft_rpi3" src="https://user-images.githubusercontent.com/33698935/167485025-5cdcd6d7-2199-4efd-b4a5-0584da45dcff.png">

**Comment by rf152** [comment]
> Is this issue still open? I see that in the changelog " Upgraded NDI library to v5.0.0" However the library in the lib/ndi folder still shows 4.6.
> 
> I believe that with NDI 5 we could possibily use NDI HX3?

Just spotted this one - apologies for the delay in responding. v2.x is on NDI 5. I can't remember whether I upgraded 3.x to NDI 5, I would have to check.

**Comment by SBCV-apegram** [comment]
Sorry to put an unnecessary comment on this issue, but I just wanted to thank @miniman13 for the simple yet genius way to test the latency of a camera. I can't tell you how long I've been struggling on this one...

**Comment by Jmcguire525** [comment]
> Just spotted this one - apologies for the delay in responding. v2.x is on NDI 5. I can't remember whether I upgraded 3.x to NDI 5, I would have to check.

Is 3.x running NDI 5?  Also, is this based on the aarch64 library within the NDI SDK or the arm (32) version?

**Comment by rf152** [comment]
3.0.x is now running on NDI5, and github actions autobuilds a 32 and 64 bit version, along with the associated libraries.

There's a bug in 3.0.1 which prevents it from interacting with the neopixel system, however I'm not sure how many others are using that beyond just me, so it may not affect you. 3.0.2 will contain the fix for that (currently testing).
