### ISSUE TITLE
Missing lib

### ISSUE THREAD

**Issue by quintendewilde** [raspberry-pi-camera/raspindi#2]
I get this error when running build.

pi@raspberrypi:~/raspindi $ sh build.sh
src/main.cpp:17:10: fatal error: libconfig.h++: No such file or directory
 #include <libconfig.h++>
          ^~~~~~~~~~~~~~~
compilation terminated.

**Comment by rf152** [comment]
You will need to install libconfig-dev for it to compile. There may be other dependencies (I can't actually remember!)
