### ISSUE TITLE
Adding audio to NDI stream from local audio capture

### ISSUE THREAD

**Issue by WatsonMLDev** [raspberry-pi-camera/raspindi#22]
Something that would really make this project shine is the ability to add audio along with the video source, this way full microphone and video setups could run just off the raspberry pi! This might be a bit much to request but if its possible I bet it would be a great addition.

Another feature could be the ability to see all the config options or pass options in the command line. The changelog shows that you can add config parameters but doesn't say where.

**Comment by rf152** [comment]
Agreed on the audio - that would make a nice addition. I don't currently have any audio capture equipment for the Raspberry Pi, and as such can't test this. Perhaps it's something I'll look at when I have an audio capture card. In the mean time, feel free to have a crack at it and raise a PR for it!

For the config options, see the example configuration file [raspindi.conf.default](https://github.com/raspberry-pi-camera/raspindi/blob/master/etc/raspindi.conf.default). This details all the options that are available.

**Comment by WatsonMLDev** [comment]
> For the config options, see the example configuration file [raspindi.conf.default](https://github.com/raspberry-pi-camera/raspindi/blob/master/etc/raspindi.conf.default). This details all the options that are available.

Thanks! I cant find this in the already compiled code on my pi, must be something I have to change before building. maybe in the future adding a way to pass arguments via the command line before starting the service would be a good feature to have.

thanks for the quick reply!

**Comment by rf152** [comment]
They're read when the program executes. The file is found in /etc/raspindi.conf on a live system.

**Comment by WatsonMLDev** [comment]
Oh I see now, thanks!
