### ISSUE TITLE
Just showing support!

### ISSUE THREAD

**Issue by cwatson2021** [raspberry-pi-camera/raspindi#23]
Sorry for putting this in the issues tracker (feel free to mark this as closed). Just wanted to say that this is super awesome as the NDI SDK isn't even available for ARM processors anymore. This really turns $30 board with the really nice high quality pi cameras into powerful tools for livestreams at events. Keep up the good work (already made a public GUI for this btw ;) )

**Comment by rf152** [comment]
I'm pleased you're finding it useful. :)
