### ISSUE TITLE
Is it possible to run multiple pi's for multiple NDI streams?

### ISSUE THREAD

**Issue by batchku** [raspberry-pi-camera/raspindi#31]
**Is your feature request related to a problem? Please describe.**
I'd like to run multiple pi's to have multiple video streams in the same network. I can do this by changing the video stream name in `main.cpp` to, for examples `Video Feed 2`, build and install again; and then I can run two.

**Describe the solution you'd like**
Currently, without doing the above, when i try this, the first camera works but the second does not; the application runs but I don't see its NDI stream.  I suspect this is because the streams have the same name?

**Describe alternatives you've considered**
Add stream name to the configuration file?

**Additional context**

**Comment by rf152** [comment]
The NDI stream takes the name of the host, so as long as your hosts are named different things (so not raspberrypi) then they should appear as separate streams.

**Comment by batchku** [comment]
Aha, got it; the parenthetical in the NDI stream name is dynamically set; that does the trick, thank you.
