### ISSUE TITLE
Camera rotation 

### ISSUE THREAD

**Issue by BrandonHortman** [raspberry-pi-camera/raspindi#7]
Is it possible to rotate the camera? 
Thanks for sharing.

![Screenshot 2021-03-30 082827 (2)](https://user-images.githubusercontent.com/76578289/112993231-f8997480-9136-11eb-8bca-228941034965.png)

**Comment by rf152** [comment]
There isn't anything specifically in the code to rotate the camera - that would require more processing as the image would have to be rotated in the software (unless there is a way of capturing the image rotated, but I don't know on that).

It may be that you can rotate it within the NDI consumer.

**Comment by rf152** [comment]
In work on another enhancement, I think I've found a way of doing this. I've reopened this bug to track it - keep your eyes open for v2.0.0

**Comment by rf152** [comment]
Brandon, this is now possible using the config parameter `rotation`. Valid values are 0, 90, 180, 270.
