### ISSUE TITLE
Raspberry PI 5 support?

### ISSUE THREAD

**Issue by jficarapi** [raspberry-pi-camera/raspindi#76]
Greetings Friends,

Feature / question:

Has anyone tried this with a Raspberry PI 5? 

Does it work with a Raspberry PI 5?

**Comment by rf152** [comment]
I don't know of any reason it shouldn't, however I don't own a Pi 5, so I can't be 100% certain.

If you have a Pi 5, I'd suggest trying it, and seeing if it will work!
